storage:
  # The type of storage to use for player data.
  # Could be: YAML, MySQL*, MongoDB*
  # * extension required
  type: MySQL
  hostname: localhost
  username: user
  password: pass
  database: skywarsreloaded
  use-ssl: true

# the number of instances of a map template that will be loaded when the server starts.
game-instances:
  default: 1
  # map1: 2
  # map2: 1

world-loader:
  # automatically use slime worlds if SlimeWorldManager (SWM) was detected.
  enable-swm: true

parties:
  allow-dispersed-parties: true