storage:
  # The type of storage to use for player data.
  # Could be: YAML, MySQL*, MongoDB*
  # * extension required
  type: MySQL
  hostname: localhost
  username: user
  password: pass
  database: skywarsreloaded
  use-ssl: true

# the number of instances of a map template that will be loaded when the server starts.
game-instances:
  default: 1
  # map1: 2
  # map2: 1

world-loader:
  # automatically use slime worlds if SlimeWorldManager (SWM) was detected.
  enable-swm: true

menus:
  join:
    # Options: NAME, NAME-REVERSED, TEAMSIZE, TEAMSIZE-REVERSED, WAITING, WAITING-REVERSED
    sort-by: TEAMSIZE

game:
  timers:
    waiting-lobby: 180
    waiting-lobby-full: 10
    waiting-cages: 30
    waiting-cages-full: 15
    ending: 20
  cages:
    separate-cages: false
  chests:
    max-items: 26
    max-items-double: 53
  solo-waiting-lobby: false

parties:
  allow-dispersed-parties: true