debugMode: false
bungeeMode: false
bungeeLobby: lobby
isLobbyServer: false
gameServers:
  - server-name:port:display name:max players:team size
gameEndCommands:
tauntCooldown: 10
enablePressurePlateJoin: true
teleportToSpawnOnJoin: false
teleportToSpawnOnWorldEnter: true
resourcepack: https://www.dropbox.com/s/8scs6c911y3mqbg/taunts-resource-pack.zip?dl=1
promptForResourcePackOnJoin: false
lobbyBoardEnabled: false
displayPlayerLevelOnXpBar: true
enabledLobbyGuard: false
economyEnabled: false
clearInventoryOnLobbyJoin: true
timeFormat: simplified
slimeworldmanager:
  enable: false
  source: file
game:
  win:
    clearInventory: true
    enableFlight: false
  kickOnWorldTeleport: true
  enableQuickDeath: true
  quickDeathY: -10
  enablePVPTimer: true
  PVPTimerTime: 10 # this is the time in seconds
  enableWinMessage: true
  enableLookDirection: true
  worldBorder:
    enabled: false
    borderSize: 400
  showHealth: true
  snowballDamage: 1
  eggDamage: 1
  ecoForWin: 5
  ecoForKill: 1
  xpForWin: 5
  winCommands: []
  xpForKill: 1
  killCommands: []
  vip1Multiplier: 2
  vip2Multiplier: 3
  vip3Multiplier: 4
  vip4Multiplier: 5
  vip5Multiplier: 10
  timeAfterMatch: 15
  waitTimer: 10
  resetTimerOnJoin: false
  kitVotingEnabled: false
  spectateEnabled: true
  maxMapSize: 400
  tauntsEnabled: true
  modifierLevel:
    speed:
    strength:
    jump: 
teams:
  useTeamChat: true
  usePlayerNames: true
  usePlayerGlassColors: true
  useTeamNumberInMenu: true
  teamCageMaterial: WOOL
  useTeamMaterialBytes: false
  standardTeamMaterialByte: 4
  useSeparateCages: true
  changeTablistNames: false
chat:
  enableFormatter: true
  limitGameChatToGame: true
  limitLobbyChatToLobby: true
  limitSpecChatToSpec: true
  externalChat:
    useExternalChat: false
    addPrefix: false  
parties:
  enabled: true
  enablePartyAndFriendsSupport: false
  maxPartySize: 4
  lobbyWorlds: []
holograms: 
  enabled: false
chests:
  loadTrappedChestsAsCenter: false
  maxItemsChest: 26
  maxItemsDoubleChest: 53 
kit:
  randPos: 0
  menuSize: 45
  randItem: NETHER_STAR
  noKitPos: 44
  noKitItem: GLASS
titles:
  enabled: true
fireworks:
  enabled: true
  per5Ticks: 1
sounds:
  enabled: true
  countdown: NOTE_BASS
  join: DOOR_OPEN
  leave: DOOR_CLOSE
  openJoinMenu: DOOR_OPEN
  openSpectateMenu: DOOR_OPEN
  openOptionsMenu: ZOMBIE_REMEDY
  openGlassMenu: GLASS
  openWinSoundMenu: FIREWORK_BLAST
  openKillSoundMenu: PIG_DEATH
  openParticleMenu: STEP_GRAVEL
  openProjectileMenu: SHOOT_ARROW
  openTauntMenu: ENDERDRAGON_WINGS
  openKitMenu: SUCCESSFUL_HIT
  openChestMenu: CHEST_OPEN
  openHealthMenu: EAT
  openTimeMenu: FUSE
  openWeatherMenu: AMBIENCE_RAIN
  openModifierMenu: SPLASH2
  confirmSelectionSound: VILLAGER_YES
  errorSound: VILLAGER_NO
signs:
  enabled: true
  blockoffline: COAL_BLOCK
  blockwaiting: EMERALD_BLOCK
  blockplaying: REDSTONE_BLOCK
  blockending: LAPIS_BLOCK
  almostfull: DIAMOND_HELMET
  threefull: GOLD_HELMET
  halffull: IRON_HELMET
  almostempty: LEATHER_HELMET
items:
  randomVoteEnabled: true
  scavengerChestEnabled: false
  joinGameItemEnabled: true
  spectateGameItemEnabled: true
  optionsItemEnabled: true
  teamSelectPosition: 2
  teamSelectItem: WATCH
  kitsEnabled: true
  kitVotePosition: 0
  kitvote: EYE_OF_ENDER
  voteEnabled: true
  votingPosition: 4
  votingItem: COMPASS
  exitGameItem: IRON_DOOR
  exitPosition: 8
  exitMenuItem: BARRIER
  prevPageItem: FEATHER
  nextPageItem: FEATHER
  chestVoteEnabled: true
  chestVotePosition: 10
  chestvote: SHIELD
  chestrandom: NETHER_STAR
  chestbasic: STONE_SWORD
  chestnormal: IRON_SWORD
  chestop: DIAMOND_SWORD
  chestscavenger: WOOD_HOE
  healthVoteEnabled: true
  healthVotePosition: 11
  healthvote: EXP_BOTTLE
  healthrandom: NETHER_STAR
  healthfive: REDSTONE
  healthten: REDSTONE
  healthfifteen: REDSTONE
  healthtwenty: REDSTONE
  nopermission: BARRIER
  timeVoteEnabled: true
  timeVotePosition: 12
  timevote: WATCH
  timerandom: NETHER_STAR
  timedawn: WATCH
  timenoon: WATCH
  timedusk: WATCH
  timemidnight: WATCH
  weatherVoteEnabled: true
  weatherVotePosition: 14
  weathervote: BLAZE_POWDER
  weatherrandom: NETHER_STAR
  weathersunny: PRISMARINE_SHARD
  weatherrain: PRISMARINE_SHARD
  weatherstorm: PRISMARINE_SHARD
  weathersnow: PRISMARINE_SHARD
  modifierVoteEnabled: true
  modifierVotePosition: 16
  modifiervote: DRAGONS_BREATH
  modifierspeed: BOOK
  modifierjump: BOOK
  modifierstrength: BOOK
  modifiernone: BOOK
  modifierrandom: NETHER_STAR
  joinselect: DIAMOND_HELMET
  singleSlot: 11
  singlemenu: REDSTONE_TORCH_ON
  teamSlot: 15
  teammenu: REDSTONE_COMPARATOR
  spectateselect: LEATHER_HELMET
  optionselect: EYE_OF_ENDER
  particleselect: BLAZE_POWDER
  particleselectslot: 11
  projectileselect: ARROW
  projectileselectslot: 12 
  killsoundselect: DIAMOND_SWORD
  killsoundselectslot: 14
  killsounditem: NOTE_BLOCK
  winsoundselect: DRAGON_EGG
  winsoundselectslot: 15
  glassselect: STAINED_GLASS
  glassselectslot: 9 
  tauntselect: SHIELD
  tauntselectslot: 17
particles:
  enabled: true
  ticksperupdate: 3
enabledMenus:
  join: true
  joinSlot: 0
  spectate: true
  spectateSlot: 4
  options: true
  optionsSlot: 8
  glass: true
  particle: true
  projectile: true
  killsound: true
  winsound: true
  taunts: true
sqldatabase:
  enabled: false
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
leaderboards:
  length: 10
  leaderboardUpdateInterval: 300
  signsEnabled: true
  headsEnabled: true
  winsLeaderboardEnabled: false
  lossesLeaderboardEnabled: false
  killsLeaderboardEnabled: false
  deathsLeaderboardEnabled: false
  xpLeaderboardEnabled: false
disable-commands:
  exceptions:
  - msg
  - r
  - sw quit
  enabled: true
disable-commands-spectate:
  exceptions:
  - msg
  - r
  - sw quit
  enabled: true
